config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  get 'favorites/index'
  devise_for :users
  root to: "homes#top"

  resources :tweets, only: [:new, :index, :show, :create, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end


   resources :users, only: [:show, :edit, :update, :destroy] do
     member do
       get :favorites
     end
     resource :relationships, only: [:create, :destroy]
     get :follows, on: :member
     get :followers, on: :member
   end

   resources :chats, only: [:show, :create]
   
   resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
     resource :group_users, only: [:create, :destroy]
   end


  get 'homes/top'
  get 'homes/about' => 'homes#about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :room

  validates :message, length: { in: 1..140 }

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :tweet

end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, dependent: :destroy
  belongs_to :owner, class_name: 'User'
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :group_image
  
  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end

  def owned_by?(user)
    owner.id == user.id
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  
  belongs_to :user
  belongs_to :group
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :tweet

  validates :comment,presence:true

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  validates :caption,presence:true,length:{maximum:200}



  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms



  # ====================自分がフォローしているユーザーとの関連 ===================================
  #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので親はfollowing_id(フォローする側)
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings, through: :active_relationships, source: :follower
  # ========================================================================================

  # ====================自分がフォローされるユーザーとの関連 ===================================
  #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので親はfollower_id(フォローされる側)
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true,  presence: true
  validates :introduction, length: { maximum: 50}


def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end


end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def show
    @user = User.find(params[:id]) #チャットする相手は誰？
    rooms = current_user.user_rooms.pluck(:room_id) #ログイン中のユーザーの部屋情報を全て取得
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end

    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @room = @chat.room
    @chats = @room.chats
    render :validater unless @chat.save
  end

  private
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
 before_action :authenticate_user!


  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.save
     redirect_to tweets_path, notice: "You have created tweet successfully."
    else
     @tweets = Tweet.all
     @user = current_user
     render 'index'
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @new_tweet = Tweet.new
    @user = @tweet.user
    @post_comment = PostComment.new
  end

  def index
    @tweets = Tweet.all
    @user = current_user
    @tweet = Tweet.new
  to  = Time.current.at_end_of_day
  from  = (to - 6.day).at_beginning_of_day
  @tweets = Tweet.includes(:favorites).sort_by {|x| x.favorites.where(created_at: from...to).size}.reverse

  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to tweets_path
  end

  private

  def tweet_params
    params.require(:tweet).permit(:caption, :image)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
    @tweet = Tweet.new
  end

  def edit
    @user = User.find(params[:id])

    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    user = User.find(current_user.id)
    user.update(user_params)
    redirect_to user_path(user)
  end

  def favorites
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id:@user.id).pluck(:tweet_id)
    @favorite_tweets =Tweet.find(favorites)
    @tweet = Tweet.new
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

private

def user_params
  params.require(:user).permit(:name, :profile_image, :introduction, :address, :birthday)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tweets/_favorites.html.erb
  <% if tweet.favorited_by?(current_user) %>
    <p>
      <%= link_to tweet_favorites_path(tweet), method: :delete do %>
        ♥<%= tweet.favorites.count %> 
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to tweet_favorites_path(tweet), method: :post do %>
        ♡<%= tweet.favorites.count %> 
      <% end %>
    </p>
  <% end %>

app/views/tweets/_postcomment.html.erb
 <% tweet.post_comments.each do |post_comment| %>
  <p><%= image_tag post_comment.user.get_profile_image(100,100) %>
     <%= post_comment.user.name %>
     <%= post_comment.created_at.strftime('%Y/%m/%d') %></p>
     <%= post_comment.comment %>
    <% if post_comment.user == current_user %>
      <%= link_to "削除", tweet_post_comment_path(post_comment.tweet, post_comment), method: :delete %>
    <% end %>
 <% end %>

<%= form_with model: [tweet, post_comment] do |f| %>
  <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>

app/views/tweets/_tweet.html.erb
<%= form_with model: tweet do |f| %>
  <h4>image</h4>
  <%= f.file_field :image, accept: "image/*" %>
  <h4>caption</h4>
  <%= f.text_area :caption %>
  <%= f.submit 'Tweetする' %>
<% end %>

<%=link_to "New Group",new_group_path %> |
<%=link_to "Groups All",groups_path %>

app/views/tweets/_tweets.html.erb
<table class="table table-user">
  <% tweets.each do |tweet| %>
    <tr>
      <td><%= image_tag tweet.get_image, size: '300x300' %></td>
    </tr>
    <tr>
      <td>
        <%= link_to(tweet.user) do %>
          <%= image_tag tweet.user.get_profile_image(100,100) %>
          <%= tweet.user.name %><br>
        <% end %>
        <%= link_to tweet.caption, tweet_path(tweet) %>
      </td>
    </tr>
    <tr>
      <td><%= render 'tweets/favorites', tweet: tweet %></td>
      <td>
        <% if current_user != tweet.user %>
          <% if tweet.user.followed_by?(current_user) %>
              <%=link_to "unfollow", user_relationships_path(tweet.user.id), method: :delete, class: 'btn btn-danger' %>
          <% else %>
              <%=link_to "follow", user_relationships_path(tweet.user.id), method: :post, class: 'btn btn-success' %>
          <% end %>
         <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/tweets/index.html.erb
<div class='container px-5 my-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3 '>
      <h2>User infomation</h2>
      <%= render 'users/info', user: current_user %>

      <h2>Tweet form</h2>
      <%= render 'tweet', tweet: @tweet %>



    </div>
    <div class='col-md-8 offset-md-1'>
     <%= render 'layouts/error', tweet: @tweet %>
     <%= render 'tweets', tweets: @tweets %>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<h1>楽しかった出来事を投稿しよう！</h1>
<%= render 'tweet', tweet: @tweet %>

app/views/tweets/show.html.erb
<div class='container px-5 my-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3 '>
      <h2>User infomation</h2>
      <%= render 'users/info', user: @user %>
      <h2>Tweet form</h2>
      <%= render 'tweet', tweet: @new_tweet %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <table class="table table-user">
       <tr>
         <td><%= image_tag @tweet.get_image, size:'400x400' %></td>
       </tr>

      <tr>
        <td>
          <%= image_tag @tweet.user.get_profile_image(100,100) %>
          <%= @tweet.user.name %>
          <%= @tweet.created_at.strftime('%Y/%m/%d') %>
          コメント件数：<%= @tweet.post_comments.count %>
        </td>
      </tr>
      <tr>
        <td>
          <%= @tweet.caption %>
         <% if @tweet.user == current_user %>
          <%= link_to "tweetを削除", tweet_path(@tweet), method: :delete %>
        <% end %>
        </td>
        <td><%= render 'tweets/favorites', tweet: @tweet %></td>
      </tr>
      <tr>
        <td>
          <%= render 'tweets/postcomment', tweet:@tweet, post_comment:@post_comment %>
        </td>
      </tr>
     </table>
   </div>
  </div>
</div>