config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  get 'favorites/index'
  devise_for :users
  root to: "homes#top"

  resources :tweets, only: [:new, :index, :show, :create, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end


   resources :users, only: [:show, :edit, :update, :destroy] do
     member do
       get :favorites
     end
     resource :relationships, only: [:create, :destroy]
     get :follows, on: :member
     get :followers, on: :member
   end

   resources :chats, only: [:show, :create]
   
   resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
     resource :group_users, only: [:create, :destroy]
   end


  get 'homes/top'
  get 'homes/about' => 'homes#about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :room

  validates :message, length: { in: 1..140 }

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :tweet

end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, dependent: :destroy
  belongs_to :owner, class_name: 'User'
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :group_image
  
  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end

  def owned_by?(user)
    owner.id == user.id
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  
  belongs_to :user
  belongs_to :group
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :tweet

  validates :comment,presence:true

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  validates :caption,presence:true,length:{maximum:200}



  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms



  # ====================自分がフォローしているユーザーとの関連 ===================================
  #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので親はfollowing_id(フォローする側)
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings, through: :active_relationships, source: :follower
  # ========================================================================================

  # ====================自分がフォローされるユーザーとの関連 ===================================
  #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので親はfollower_id(フォローされる側)
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true,  presence: true
  validates :introduction, length: { maximum: 50}


def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end


end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def show
    @user = User.find(params[:id]) #チャットする相手は誰？
    rooms = current_user.user_rooms.pluck(:room_id) #ログイン中のユーザーの部屋情報を全て取得
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end

    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @room = @chat.room
    @chats = @room.chats
    render :validater unless @chat.save
  end

  private
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
    @tweet = Tweet.new
  end

  def edit
    @user = User.find(params[:id])

    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    user = User.find(current_user.id)
    user.update(user_params)
    redirect_to user_path(user)
  end

  def favorites
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id:@user.id).pluck(:tweet_id)
    @favorite_tweets =Tweet.find(favorites)
    @tweet = Tweet.new
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

private

def user_params
  params.require(:user).permit(:name, :profile_image, :introduction, :address, :birthday)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/_message.html.erb
<div class="chat-messages">
  <% chats.each do |chat| %>
    <% if chat.user_id == current_user.id %>
      <div class="message self">
        <div class="message-body">
          <%= chat.message %>
        </div>
      </div>
    <% else %>
      <div class="message other">
        <div class="message-sender"><%= chat.user.name %></div>
        <div class="message-body">
          <%= chat.message %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/chats/create.js.erb
$('.message').html("<%= j(render 'chats/message', chats: @chats) %>");
$('input[type=text]').val("")

app/views/chats/show.html.erb
<div class="chat-container">
  <div class="chat-topbar">
    <h2><%= @user.name %> さんとのチャット</h2>
  </div>
  <div class="message">
    <%= render "chats/message", chats: @chats %>
  </div>

  <div class="chat-form">
    <%= form_with model: @chat, data: {remote: true} do |f| %>
      <%= f.text_field :message, placeholder: "メッセージを入力してください", autocomplete: "off" %>
      <%= f.hidden_field :room_id, value: @room.id %>
      <%= f.submit "送信" %>
    <% end %>
  </div>
</div>

app/views/chats/validator.js.erb
$('.errors').html("<%= j(render 'layouts/errors', obj: @chat) %>");

app/views/users/_info.html.erb
<table class='table'>
  <tr>
  <th><%= image_tag user.get_profile_image(100,100) %></th>
  <th>
    <% if current_user != user && current_user.followed_by?(user) && user.followed_by?(current_user) %>
      <%= link_to 'DM', chat_path(user.id), class: "ml-3, btn btn-info" %>
    <% end %>
  </th>
  </tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>address</th>
    <th><%= user.address %></th>
  </tr>
  <tr>
    <th>birthday</th>
    <th><%= user.birthday %></th>
  </tr>
   <tr>
  <th>follow
    <%= link_to follows_user_path(user) do %>
      <%= "#{user.active_relationships.count}" %>
    <% end %>
  </th>
  <th>follower
    <%= link_to followers_user_path(user) do %>
     <%= "#{user.passive_relationships.count}" %>
    <% end %>
  </th>
 </tr>
  <tr>
    <th>
       <% if current_user != user %>
          <% if user.followed_by?(current_user) %>
              <p><%=link_to "unfollow", user_relationships_path(user.id), method: :delete, class: 'btn btn-danger' %></p>
          <% else %>
              <p><%=link_to "follow", user_relationships_path(user.id), method: :post, class: 'btn btn-success' %></p>
          <% end %>
      <% end %>
    </th>
   <th><%=link_to"favorite list",favorites_user_path(user), class: 'btn btn-primary' %></th>

  </tr>

</table>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= form_with model: @user do |f| %>
  <div class = "form-group">
    <label for="inputName">Name</label><br>
  <%= f.text_field :name, autofocus: true, id:"inputName form-control" ,class: "inputName form-control" %>
  </div>


  <div class = "form-group">
    <label for="inputImage">Image</label><br>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  </div>

<div class = "form-group">
  <label for="inputIntroduction">Introduction</label><br>
  <%= f.text_area :introduction, autofocus: true, id:"inputintroduction",class: "inputIntroduction form-control"  %>
</div>


  <div class = "form-group">
    <label for="inputAddress">Address</label><br>
  <%= f.text_field :address, autofocus: true, id:"inputAddress form-control" ,class: "inputAddress form-control" %>
  </div>

  <div class = "form-group">
    <label for="inputBirthday">Birthday</label><br>
  <%= f.text_field :birthday, autofocus: true, id:"inputBirthday form-control" ,class: "inputBirthday form-control" %>
  </div>



<div class = "form-group">
  <%= f.submit "Update User",class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/users/favorites.html.erb
<div class='container px-5 my-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3 '>
      <h2>User infomation</h2>
      <%= render 'users/info', user: @user %>
      <h2>Tweet form</h2>
      <%= render 'tweets/tweet', tweet: @tweet %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>いいね一覧</h2>
     <%= render 'tweets/tweets', tweets: @favorite_tweets %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<h1>Follower Users</h1>
  <% if @users.blank? %>
  <p>ユーザーはいません</p>
<% else %>
  <% @users.each do |user| %>
     <table class='table table-hover table-inverse'>
       <tr>
         <th>image</th>
         <th>name</th>
         <th colspan="3"></th>
        </tr>

      <tbody>
        <tr>
          <td><%= link_to(user) do %>
            <%= image_tag user.get_profile_image(100,100) %>
            <% end %>
          </td>
          <td><%= user.name %></td>
          <td><%= "フォロー数: #{user.active_relationships.count}" %></td>
          <td><%= "フォロワー数: #{user.passive_relationships.count}" %></td>
          <td><%= link_to 'Show', user %></td>
        </tr>
      </tbody>
     </table>
  <% end %>
<% end %>

app/views/users/follows.html.erb
<h1>Follow Users</h1>
<% if @users.blank? %>
<p>ユーザーはいません</p>
<% else %>
　<% @users.each do |user| %>
   <table class='table table-hover table-inverse'>
     <tr>
       <th>image</th>
       <th>name</th>
       <th colspan="3"></th>
      </tr>

    <tbody>
      <tr>
        <td><%= link_to(user) do %>
          <%= image_tag user.get_profile_image(100,100) %>
          <% end %>
        </td>
        <td><%= user.name %></td>
        <td><%= "フォロー数: #{user.active_relationships.count}" %></td>
        <td><%= "フォロワー数: #{user.passive_relationships.count}" %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    </tbody>
   </table>
  <% end %>
<% end %>

app/views/users/show.html.erb
<!-- ユーザーの詳細 -->
<div class='container px-5 my-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3 '>
      <h2>User infomation</h2>
      <%= render 'info', user: @user %>
      <h2>Tweet form</h2>
      <%= render 'tweets/tweet', tweet: @tweet %>
    </div>


    <div class='col-md-8 offset-md-1'>
     <table class="table table-user">
     <% @tweets.each do |tweet| %>
      <div>
        <p>
           <%= image_tag tweet.get_image, size: '500x500' %>
        </p>
        <p>
          <%= link_to tweet_path(tweet.id) do %>
           <%= image_tag tweet.user.get_profile_image(100,100) %>
           <%= tweet.user.name %>
          <% end %>
        </p>
        <p><%= tweet.caption %></p>
     </div>
    <% end %>
  </div>
</div>